### ISSUE TITLE
Review release tooling

### ISSUE THREAD

**Issue by haydentherapper** [haydentherapper/timestamp-authority#6]
* Do we need the OIDC setup tooling?
* Review release.mk and Makefile

**Comment by haydentherapper** [comment]
@cpanato Would you be able to help with this review? I copied over the Makefile and release directory from Rekor, and I've tried to update it accordingly, but I'm not familiar with these scripts so I might have missed something.

Relevant links: https://github.com/haydentherapper/timestamp-authority/blob/main/Makefile, https://github.com/haydentherapper/timestamp-authority/tree/main/release

I removed any references to Rekor and Trillian. There's also a lot of Makefile targets that I'm not sure if we need, like `ko` and `deploy`.

**Comment by cpanato** [comment]
@haydentherapper sure, will work on this

**Comment by cpanato** [comment]
PR: https://github.com/haydentherapper/timestamp-authority/pull/8
